name: Semantic CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Semantic Versioning
        id: versioning
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.versioning.outputs.new_tag }}
          name: Pre-release ${{ steps.versioning.outputs.new_version }}
          generateReleaseNotes: true
