name: Semantic CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Semantic Versioning
        id: versioning
        uses: paulhatch/semantic-version@v4.0.2
        with:
          branch: main
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: Release ${{ steps.versioning.outputs.version }}
          body: ${{ steps.versioning.outputs.changed }}
          draft: false
          prerelease: false
